/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "buffer_gen_sintetizado.v:1" *)
module buffer_gen_sintetizado(clk, data_bus, data_out_bus_sint, control_out_sint);
  (* src = "buffer_gen_sintetizado.v:11" *)
  wire _00_;
  wire _01_;
  wire _02_;
  (* src = "buffer_gen_sintetizado.v:5" *)
  input clk;
  (* src = "buffer_gen_sintetizado.v:8" *)
  output control_out_sint;
  (* src = "buffer_gen_sintetizado.v:6" *)
  input [3:0] data_bus;
  (* src = "buffer_gen_sintetizado.v:7" *)
  output [3:0] data_out_bus_sint;
  NOR _03_ (
    .A(data_bus[2]),
    .B(data_bus[3]),
    .Y(_01_)
  );
  NOR _04_ (
    .A(data_bus[0]),
    .B(data_bus[1]),
    .Y(_02_)
  );
  NAND _05_ (
    .A(_01_),
    .B(_02_),
    .Y(_00_)
  );
  (* src = "buffer_gen_sintetizado.v:11" *)
  DFF _06_ (
    .C(clk),
    .D(data_bus[0]),
    .Q(data_out_bus_sint[0])
  );
  (* src = "buffer_gen_sintetizado.v:11" *)
  DFF _07_ (
    .C(clk),
    .D(data_bus[1]),
    .Q(data_out_bus_sint[1])
  );
  (* src = "buffer_gen_sintetizado.v:11" *)
  DFF _08_ (
    .C(clk),
    .D(data_bus[2]),
    .Q(data_out_bus_sint[2])
  );
  (* src = "buffer_gen_sintetizado.v:11" *)
  DFF _09_ (
    .C(clk),
    .D(data_bus[3]),
    .Q(data_out_bus_sint[3])
  );
  (* src = "buffer_gen_sintetizado.v:11" *)
  DFF _10_ (
    .C(clk),
    .D(_00_),
    .Q(control_out_sint)
  );
endmodule

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "generate_mod_sintetizado.v:3" *)
module generate_mod_sintetizado(data_bus, clk, data_out_bus_sint, control_out_sint);
  (* src = "generate_mod_sintetizado.v:8" *)
  input clk;
  (* src = "generate_mod_sintetizado.v:10" *)
  output [3:0] control_out_sint;
  (* src = "generate_mod_sintetizado.v:7" *)
  input [15:0] data_bus;
  (* src = "generate_mod_sintetizado.v:9" *)
  output [15:0] data_out_bus_sint;
  (* module_not_derived = 32'd1 *)
  (* src = "generate_mod_sintetizado.v:16" *)
  buffer_gen_sintetizado \BUFFER_GEN_1[0].buff  (
    .clk(clk),
    .control_out_sint(control_out_sint[3]),
    .data_bus(data_bus[3:0]),
    .data_out_bus_sint(data_out_bus_sint[15:12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "generate_mod_sintetizado.v:16" *)
  buffer_gen_sintetizado \BUFFER_GEN_1[1].buff  (
    .clk(clk),
    .control_out_sint(control_out_sint[2]),
    .data_bus(data_bus[7:4]),
    .data_out_bus_sint(data_out_bus_sint[11:8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "generate_mod_sintetizado.v:16" *)
  buffer_gen_sintetizado \BUFFER_GEN_1[2].buff  (
    .clk(clk),
    .control_out_sint(control_out_sint[1]),
    .data_bus(data_bus[11:8]),
    .data_out_bus_sint(data_out_bus_sint[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "generate_mod_sintetizado.v:16" *)
  buffer_gen_sintetizado \BUFFER_GEN_1[3].buff  (
    .clk(clk),
    .control_out_sint(control_out_sint[0]),
    .data_bus(data_bus[15:12]),
    .data_out_bus_sint(data_out_bus_sint[3:0])
  );
endmodule
