/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "state_machine_sintetizado.v:1" *)
module state_machine_sintetizado(reset, clk, data_bus, error_sint);
  (* src = "state_machine_sintetizado.v:24" *)
  wire [3:0] _000_;
  (* src = "state_machine_sintetizado.v:24" *)
  wire _001_;
  (* src = "state_machine_sintetizado.v:24" *)
  wire [3:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  (* src = "state_machine_sintetizado.v:16" *)
  wire [3:0] buffer;
  (* src = "state_machine_sintetizado.v:6" *)
  input clk;
  (* src = "state_machine_sintetizado.v:12" *)
  wire [3:0] counter;
  (* src = "state_machine_sintetizado.v:7" *)
  input [15:0] data_bus;
  (* src = "state_machine_sintetizado.v:8" *)
  output error_sint;
  (* src = "state_machine_sintetizado.v:16" *)
  wire [3:0] f_code;
  (* src = "state_machine_sintetizado.v:15" *)
  wire [31:0] k;
  (* src = "state_machine_sintetizado.v:5" *)
  input reset;
  (* onehot = 32'd1 *)
  wire [4:0] state;
  NOT _115_ (
    .A(state[4]),
    .Y(_054_)
  );
  NOT _116_ (
    .A(state[1]),
    .Y(_055_)
  );
  NOT _117_ (
    .A(counter[0]),
    .Y(_056_)
  );
  NOT _118_ (
    .A(counter[1]),
    .Y(_057_)
  );
  NOT _119_ (
    .A(counter[2]),
    .Y(_058_)
  );
  NOT _120_ (
    .A(counter[3]),
    .Y(_059_)
  );
  NOT _121_ (
    .A(error_sint),
    .Y(_060_)
  );
  NOT _122_ (
    .A(state[0]),
    .Y(_061_)
  );
  NOT _123_ (
    .A(f_code[1]),
    .Y(_062_)
  );
  NOT _124_ (
    .A(reset),
    .Y(_006_)
  );
  NOT _125_ (
    .A(f_code[3]),
    .Y(_063_)
  );
  NOT _126_ (
    .A(f_code[2]),
    .Y(_064_)
  );
  NOT _127_ (
    .A(f_code[0]),
    .Y(_065_)
  );
  NOT _128_ (
    .A(data_bus[12]),
    .Y(_066_)
  );
  NOT _129_ (
    .A(data_bus[13]),
    .Y(_067_)
  );
  NOT _130_ (
    .A(data_bus[14]),
    .Y(_068_)
  );
  NOT _131_ (
    .A(data_bus[15]),
    .Y(_069_)
  );
  NOT _132_ (
    .A(data_bus[2]),
    .Y(_070_)
  );
  NOT _133_ (
    .A(data_bus[3]),
    .Y(_071_)
  );
  NOR _134_ (
    .A(_062_),
    .B(data_bus[13]),
    .Y(_072_)
  );
  NOR _135_ (
    .A(f_code[1]),
    .B(_067_),
    .Y(_073_)
  );
  NOR _136_ (
    .A(_072_),
    .B(_073_),
    .Y(_074_)
  );
  NOR _137_ (
    .A(_065_),
    .B(data_bus[12]),
    .Y(_075_)
  );
  NOR _138_ (
    .A(f_code[0]),
    .B(_066_),
    .Y(_076_)
  );
  NOR _139_ (
    .A(_075_),
    .B(_076_),
    .Y(_077_)
  );
  NAND _140_ (
    .A(_074_),
    .B(_077_),
    .Y(_078_)
  );
  NOR _141_ (
    .A(_063_),
    .B(data_bus[15]),
    .Y(_079_)
  );
  NOR _142_ (
    .A(f_code[3]),
    .B(_069_),
    .Y(_080_)
  );
  NOR _143_ (
    .A(_079_),
    .B(_080_),
    .Y(_081_)
  );
  NOR _144_ (
    .A(_064_),
    .B(data_bus[14]),
    .Y(_082_)
  );
  NOR _145_ (
    .A(f_code[2]),
    .B(_068_),
    .Y(_083_)
  );
  NOR _146_ (
    .A(_082_),
    .B(_083_),
    .Y(_084_)
  );
  NAND _147_ (
    .A(_081_),
    .B(_084_),
    .Y(_085_)
  );
  NOR _148_ (
    .A(_078_),
    .B(_085_),
    .Y(_086_)
  );
  NAND _149_ (
    .A(reset),
    .B(_086_),
    .Y(_087_)
  );
  NAND _150_ (
    .A(counter[1]),
    .B(data_bus[1]),
    .Y(_088_)
  );
  NOT _151_ (
    .A(_088_),
    .Y(_089_)
  );
  NOR _152_ (
    .A(counter[1]),
    .B(data_bus[1]),
    .Y(_090_)
  );
  NOT _153_ (
    .A(_090_),
    .Y(_091_)
  );
  NAND _154_ (
    .A(_088_),
    .B(_091_),
    .Y(_092_)
  );
  NOR _155_ (
    .A(_089_),
    .B(_090_),
    .Y(_093_)
  );
  NAND _156_ (
    .A(counter[0]),
    .B(data_bus[0]),
    .Y(_094_)
  );
  NOT _157_ (
    .A(_094_),
    .Y(_095_)
  );
  NOR _158_ (
    .A(counter[0]),
    .B(data_bus[0]),
    .Y(_096_)
  );
  NOT _159_ (
    .A(_096_),
    .Y(_097_)
  );
  NAND _160_ (
    .A(_094_),
    .B(_097_),
    .Y(_098_)
  );
  NOR _161_ (
    .A(_095_),
    .B(_096_),
    .Y(_099_)
  );
  NOR _162_ (
    .A(_093_),
    .B(_099_),
    .Y(_100_)
  );
  NAND _163_ (
    .A(_092_),
    .B(_098_),
    .Y(_101_)
  );
  NOR _164_ (
    .A(_059_),
    .B(data_bus[3]),
    .Y(_102_)
  );
  NAND _165_ (
    .A(counter[3]),
    .B(_071_),
    .Y(_103_)
  );
  NOR _166_ (
    .A(counter[3]),
    .B(_071_),
    .Y(_104_)
  );
  NAND _167_ (
    .A(_059_),
    .B(data_bus[3]),
    .Y(_105_)
  );
  NOR _168_ (
    .A(_102_),
    .B(_104_),
    .Y(_106_)
  );
  NAND _169_ (
    .A(_103_),
    .B(_105_),
    .Y(_107_)
  );
  NOR _170_ (
    .A(_058_),
    .B(data_bus[2]),
    .Y(_108_)
  );
  NAND _171_ (
    .A(counter[2]),
    .B(_070_),
    .Y(_109_)
  );
  NOR _172_ (
    .A(counter[2]),
    .B(_070_),
    .Y(_110_)
  );
  NAND _173_ (
    .A(_058_),
    .B(data_bus[2]),
    .Y(_111_)
  );
  NOR _174_ (
    .A(_108_),
    .B(_110_),
    .Y(_112_)
  );
  NAND _175_ (
    .A(_109_),
    .B(_111_),
    .Y(_113_)
  );
  NOR _176_ (
    .A(_107_),
    .B(_113_),
    .Y(_114_)
  );
  NAND _177_ (
    .A(_106_),
    .B(_112_),
    .Y(_008_)
  );
  NOR _178_ (
    .A(_101_),
    .B(_008_),
    .Y(_009_)
  );
  NAND _179_ (
    .A(_100_),
    .B(_114_),
    .Y(_010_)
  );
  NOR _180_ (
    .A(_087_),
    .B(_010_),
    .Y(_011_)
  );
  NOT _181_ (
    .A(_011_),
    .Y(_012_)
  );
  NOR _182_ (
    .A(state[4]),
    .B(state[1]),
    .Y(_013_)
  );
  NAND _183_ (
    .A(_054_),
    .B(_055_),
    .Y(_014_)
  );
  NAND _184_ (
    .A(_011_),
    .B(_014_),
    .Y(_015_)
  );
  NAND _185_ (
    .A(state[0]),
    .B(reset),
    .Y(_016_)
  );
  NAND _186_ (
    .A(_015_),
    .B(_016_),
    .Y(_007_)
  );
  NAND _187_ (
    .A(_062_),
    .B(reset),
    .Y(_002_[1])
  );
  NAND _188_ (
    .A(reset),
    .B(_063_),
    .Y(_002_[3])
  );
  NAND _189_ (
    .A(reset),
    .B(_064_),
    .Y(_002_[2])
  );
  NOR _190_ (
    .A(state[3]),
    .B(state[2]),
    .Y(_017_)
  );
  NAND _191_ (
    .A(_013_),
    .B(_017_),
    .Y(_018_)
  );
  NOT _192_ (
    .A(_018_),
    .Y(_019_)
  );
  NOR _193_ (
    .A(_010_),
    .B(_019_),
    .Y(_020_)
  );
  NAND _194_ (
    .A(_009_),
    .B(_018_),
    .Y(_021_)
  );
  NAND _195_ (
    .A(_013_),
    .B(_018_),
    .Y(_022_)
  );
  NAND _196_ (
    .A(_021_),
    .B(_022_),
    .Y(_023_)
  );
  NAND _197_ (
    .A(counter[0]),
    .B(_023_),
    .Y(_024_)
  );
  NOR _198_ (
    .A(counter[0]),
    .B(_020_),
    .Y(_025_)
  );
  NOR _199_ (
    .A(_087_),
    .B(_025_),
    .Y(_026_)
  );
  NAND _200_ (
    .A(_024_),
    .B(_026_),
    .Y(_027_)
  );
  NAND _201_ (
    .A(_016_),
    .B(_027_),
    .Y(_000_[0])
  );
  NAND _202_ (
    .A(_061_),
    .B(reset),
    .Y(_028_)
  );
  NOR _203_ (
    .A(state[0]),
    .B(_087_),
    .Y(_029_)
  );
  NOR _204_ (
    .A(_009_),
    .B(_022_),
    .Y(_030_)
  );
  NOR _205_ (
    .A(_056_),
    .B(_057_),
    .Y(_031_)
  );
  NAND _206_ (
    .A(_020_),
    .B(_031_),
    .Y(_032_)
  );
  NOR _207_ (
    .A(_057_),
    .B(_023_),
    .Y(_033_)
  );
  NOR _208_ (
    .A(_021_),
    .B(_031_),
    .Y(_034_)
  );
  NOR _209_ (
    .A(_033_),
    .B(_034_),
    .Y(_035_)
  );
  NAND _210_ (
    .A(_056_),
    .B(_057_),
    .Y(_036_)
  );
  NAND _211_ (
    .A(_029_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _212_ (
    .A(_035_),
    .B(_037_),
    .Y(_000_[1])
  );
  NAND _213_ (
    .A(counter[2]),
    .B(_031_),
    .Y(_038_)
  );
  NOT _214_ (
    .A(_038_),
    .Y(_039_)
  );
  NOR _215_ (
    .A(_021_),
    .B(_038_),
    .Y(_040_)
  );
  NAND _216_ (
    .A(_020_),
    .B(_039_),
    .Y(_041_)
  );
  NOR _217_ (
    .A(_030_),
    .B(_040_),
    .Y(_042_)
  );
  NOT _218_ (
    .A(_042_),
    .Y(_043_)
  );
  NAND _219_ (
    .A(_058_),
    .B(_032_),
    .Y(_044_)
  );
  NAND _220_ (
    .A(_029_),
    .B(_044_),
    .Y(_045_)
  );
  NOR _221_ (
    .A(_043_),
    .B(_045_),
    .Y(_000_[2])
  );
  NOR _222_ (
    .A(_059_),
    .B(_042_),
    .Y(_046_)
  );
  NAND _223_ (
    .A(_059_),
    .B(_041_),
    .Y(_047_)
  );
  NAND _224_ (
    .A(_029_),
    .B(_047_),
    .Y(_048_)
  );
  NOR _225_ (
    .A(_046_),
    .B(_048_),
    .Y(_000_[3])
  );
  NAND _226_ (
    .A(reset),
    .B(_065_),
    .Y(_002_[0])
  );
  NAND _227_ (
    .A(_010_),
    .B(_018_),
    .Y(_049_)
  );
  NOR _228_ (
    .A(_060_),
    .B(_018_),
    .Y(_050_)
  );
  NAND _229_ (
    .A(_086_),
    .B(_049_),
    .Y(_051_)
  );
  NOR _230_ (
    .A(_050_),
    .B(_051_),
    .Y(_052_)
  );
  NOR _231_ (
    .A(_028_),
    .B(_052_),
    .Y(_001_)
  );
  NOR _232_ (
    .A(_087_),
    .B(_049_),
    .Y(_003_)
  );
  NAND _233_ (
    .A(reset),
    .B(_018_),
    .Y(_053_)
  );
  NOR _234_ (
    .A(_086_),
    .B(_053_),
    .Y(_005_)
  );
  NOR _235_ (
    .A(_012_),
    .B(_017_),
    .Y(_004_)
  );
  DFF _236_ (
    .C(clk),
    .D(_006_),
    .Q(state[0])
  );
  DFF _237_ (
    .C(clk),
    .D(_003_),
    .Q(state[1])
  );
  DFF _238_ (
    .C(clk),
    .D(_004_),
    .Q(state[2])
  );
  DFF _239_ (
    .C(clk),
    .D(_007_),
    .Q(state[3])
  );
  DFF _240_ (
    .C(clk),
    .D(_005_),
    .Q(state[4])
  );
  (* src = "state_machine_sintetizado.v:24" *)
  DFF _241_ (
    .C(clk),
    .D(_000_[0]),
    .Q(counter[0])
  );
  (* src = "state_machine_sintetizado.v:24" *)
  DFF _242_ (
    .C(clk),
    .D(_000_[1]),
    .Q(counter[1])
  );
  (* src = "state_machine_sintetizado.v:24" *)
  DFF _243_ (
    .C(clk),
    .D(_000_[2]),
    .Q(counter[2])
  );
  (* src = "state_machine_sintetizado.v:24" *)
  DFF _244_ (
    .C(clk),
    .D(_000_[3]),
    .Q(counter[3])
  );
  (* src = "state_machine_sintetizado.v:24" *)
  DFF _245_ (
    .C(clk),
    .D(_001_),
    .Q(error_sint)
  );
  (* src = "state_machine_sintetizado.v:24" *)
  DFF _246_ (
    .C(clk),
    .D(_002_[0]),
    .Q(f_code[0])
  );
  (* src = "state_machine_sintetizado.v:24" *)
  DFF _247_ (
    .C(clk),
    .D(_002_[1]),
    .Q(f_code[1])
  );
  (* src = "state_machine_sintetizado.v:24" *)
  DFF _248_ (
    .C(clk),
    .D(_002_[2]),
    .Q(f_code[2])
  );
  (* src = "state_machine_sintetizado.v:24" *)
  DFF _249_ (
    .C(clk),
    .D(_002_[3]),
    .Q(f_code[3])
  );
  assign buffer = data_bus[3:0];
  assign k = 32'd4;
endmodule
