/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "./src/mux2a1_2b_interno/mux2a1_2b_interno.v:1" *)
module mux2a1_2b_interno(clk, reset_L, selector, valid_0, valid_1, data_in0, data_in1, valid_out_estructural, data_estructural);
  (* src = "./src/mux2a1_2b_interno/mux2a1_2b_interno.v:26" *)
  wire [1:0] _00_;
  (* src = "./src/mux2a1_2b_interno/mux2a1_2b_interno.v:26" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  (* src = "./src/mux2a1_2b_interno/mux2a1_2b_interno.v:1" *)
  input clk;
  (* src = "./src/mux2a1_2b_interno/mux2a1_2b_interno.v:9" *)
  output [1:0] data_estructural;
  (* src = "./src/mux2a1_2b_interno/mux2a1_2b_interno.v:6" *)
  input [1:0] data_in0;
  (* src = "./src/mux2a1_2b_interno/mux2a1_2b_interno.v:7" *)
  input [1:0] data_in1;
  (* src = "./src/mux2a1_2b_interno/mux2a1_2b_interno.v:2" *)
  input reset_L;
  (* init = 2'h0 *)
  (* src = "./src/mux2a1_2b_interno/mux2a1_2b_interno.v:11" *)
  (* unused_bits = "0 1" *)
  wire [1:0] salMux1;
  (* src = "./src/mux2a1_2b_interno/mux2a1_2b_interno.v:3" *)
  input selector;
  (* src = "./src/mux2a1_2b_interno/mux2a1_2b_interno.v:4" *)
  input valid_0;
  (* src = "./src/mux2a1_2b_interno/mux2a1_2b_interno.v:5" *)
  input valid_1;
  (* src = "./src/mux2a1_2b_interno/mux2a1_2b_interno.v:8" *)
  output valid_out_estructural;
  NAND _23_ (
    .A(_11_),
    .B(_12_),
    .Y(_13_)
  );
  NOR _24_ (
    .A(_10_),
    .B(_13_),
    .Y(_14_)
  );
  NAND _25_ (
    .A(_03_),
    .B(_10_),
    .Y(_15_)
  );
  NAND _26_ (
    .A(reset_L),
    .B(_15_),
    .Y(_16_)
  );
  NOR _27_ (
    .A(_14_),
    .B(_16_),
    .Y(_00_[0])
  );
  NAND _28_ (
    .A(selector),
    .B(data_in1[1]),
    .Y(_17_)
  );
  NAND _29_ (
    .A(_02_),
    .B(data_in0[1]),
    .Y(_18_)
  );
  NAND _30_ (
    .A(_17_),
    .B(_18_),
    .Y(_19_)
  );
  NOR _31_ (
    .A(_10_),
    .B(_19_),
    .Y(_20_)
  );
  NAND _32_ (
    .A(_04_),
    .B(_10_),
    .Y(_21_)
  );
  NAND _33_ (
    .A(reset_L),
    .B(_21_),
    .Y(_22_)
  );
  NOR _34_ (
    .A(_20_),
    .B(_22_),
    .Y(_00_[1])
  );
  NOR _35_ (
    .A(_05_),
    .B(_10_),
    .Y(_01_)
  );
  NOT _36_ (
    .A(selector),
    .Y(_02_)
  );
  NOT _37_ (
    .A(data_estructural[0]),
    .Y(_03_)
  );
  NOT _38_ (
    .A(data_estructural[1]),
    .Y(_04_)
  );
  NOT _39_ (
    .A(reset_L),
    .Y(_05_)
  );
  NOT _40_ (
    .A(valid_0),
    .Y(_06_)
  );
  NAND _41_ (
    .A(selector),
    .B(valid_1),
    .Y(_07_)
  );
  NOT _42_ (
    .A(_07_),
    .Y(_08_)
  );
  NOR _43_ (
    .A(selector),
    .B(_06_),
    .Y(_09_)
  );
  NOR _44_ (
    .A(_08_),
    .B(_09_),
    .Y(_10_)
  );
  NAND _45_ (
    .A(selector),
    .B(data_in1[0]),
    .Y(_11_)
  );
  NAND _46_ (
    .A(_02_),
    .B(data_in0[0]),
    .Y(_12_)
  );
  (* src = "./src/mux2a1_2b_interno/mux2a1_2b_interno.v:26" *)
  DFF _47_ (
    .C(clk),
    .D(_01_),
    .Q(valid_out_estructural)
  );
  (* src = "./src/mux2a1_2b_interno/mux2a1_2b_interno.v:26" *)
  DFF _48_ (
    .C(clk),
    .D(_00_[0]),
    .Q(data_estructural[0])
  );
  (* src = "./src/mux2a1_2b_interno/mux2a1_2b_interno.v:26" *)
  DFF _49_ (
    .C(clk),
    .D(_00_[1]),
    .Q(data_estructural[1])
  );
endmodule

(* top =  1  *)
(* src = "./src/sintetizado2a1_4b_cmos/sintetizado2a1_4b_cmos.v:3" *)
module sintetizado2a1_4b_cmos(clk, reset_L, selector, valid_0, valid_1, data_in0, data_in1, valid_out_estructural, data_estructural);
  (* src = "./src/sintetizado2a1_4b_cmos/sintetizado2a1_4b_cmos.v:3" *)
  input clk;
  (* src = "./src/sintetizado2a1_4b_cmos/sintetizado2a1_4b_cmos.v:11" *)
  output [3:0] data_estructural;
  (* src = "./src/sintetizado2a1_4b_cmos/sintetizado2a1_4b_cmos.v:8" *)
  input [3:0] data_in0;
  (* src = "./src/sintetizado2a1_4b_cmos/sintetizado2a1_4b_cmos.v:9" *)
  input [3:0] data_in1;
  (* src = "./src/sintetizado2a1_4b_cmos/sintetizado2a1_4b_cmos.v:4" *)
  input reset_L;
  (* src = "./src/sintetizado2a1_4b_cmos/sintetizado2a1_4b_cmos.v:5" *)
  input selector;
  (* src = "./src/sintetizado2a1_4b_cmos/sintetizado2a1_4b_cmos.v:6" *)
  input valid_0;
  (* src = "./src/sintetizado2a1_4b_cmos/sintetizado2a1_4b_cmos.v:7" *)
  input valid_1;
  (* src = "./src/sintetizado2a1_4b_cmos/sintetizado2a1_4b_cmos.v:10" *)
  output valid_out_estructural;
  (* module_not_derived = 32'd1 *)
  (* src = "./src/sintetizado2a1_4b_cmos/sintetizado2a1_4b_cmos.v:13" *)
  mux2a1_2b_interno mux0 (
    .clk(clk),
    .data_estructural(data_estructural[3:2]),
    .data_in0(data_in0[3:2]),
    .data_in1(data_in1[3:2]),
    .reset_L(reset_L),
    .selector(selector),
    .valid_0(valid_0),
    .valid_1(valid_1),
    .valid_out_estructural(valid_out_estructural)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/sintetizado2a1_4b_cmos/sintetizado2a1_4b_cmos.v:24" *)
  mux2a1_2b_interno mux1 (
    .clk(clk),
    .data_estructural(data_estructural[1:0]),
    .data_in0(data_in0[1:0]),
    .data_in1(data_in1[1:0]),
    .reset_L(reset_L),
    .selector(selector),
    .valid_0(valid_0),
    .valid_1(valid_1),
    .valid_out_estructural(valid_out_estructural)
  );
endmodule
