/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "mux_synth.v:1" *)
module mux_synth(clk, reset_L, selector, data_in0, data_in1, data_out);
  (* src = "mux_synth.v:19" *)
  wire [1:0] _0_;
  (* src = "mux_synth.v:1" *)
  input clk;
  (* src = "mux_synth.v:4" *)
  input [1:0] data_in0;
  (* src = "mux_synth.v:5" *)
  input [1:0] data_in1;
  (* src = "mux_synth.v:6" *)
  output [1:0] data_out;
  reg [1:0] data_out;
  (* src = "mux_synth.v:2" *)
  input reset_L;
  (* init = 2'h0 *)
  (* src = "mux_synth.v:8" *)
  wire [1:0] salMux1;
  (* src = "mux_synth.v:3" *)
  input selector;
  assign _0_[0] = reset_L ? (* src = "mux_synth.v:21" *) salMux1[0] : 1'h0;
  assign _0_[1] = reset_L ? (* src = "mux_synth.v:21" *) salMux1[1] : 1'h0;
  assign salMux1[0] = selector ? (* src = "mux_synth.v:13" *) data_in1[0] : data_in0[0];
  assign salMux1[1] = selector ? (* src = "mux_synth.v:13" *) data_in1[1] : data_in0[1];
  (* src = "mux_synth.v:19" *)
  always @(posedge clk)
      data_out[0] <= _0_[0];
  (* src = "mux_synth.v:19" *)
  always @(posedge clk)
      data_out[1] <= _0_[1];
endmodule
